name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Unity
      uses: hanaytug/unity-installer@v1.1.0
      with:
        unity-version: 2022.3.11f1
        unity-activate-license: false
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
